#!/usr/bin/env bash
# installing and setting up nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee -a /var/www/html/index.nginx-debian.html
sudo service nginx start
