#!/usr/bin/env bash
# configuring an nginx server with a custom 404 page that contains a string

apt update -y
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
RDRT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4"
sed -i "24i $RDRT" /etc/nginx/sites-available/default
NOT_FOUND="\\\terror_page 404 /404.html;\n\
        location = /404.html {\n\
                root /var/www/html;\n\
                internal;\
        }"
sed -i "26i $NOT_FOUND" /etc/nginx/sites-available/default
STR="Ceci n'est pas une page"
echo "${STR}" > /var/www/html/404.html
service nginx restart