#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

apt -y update
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
custom_header="\\\tadd_header X-Served-By \$hostname;\n"
sed -i "17i $custom_header" /etc/nginx/nginx.conf
service nginx restart
