#!/usr/bin/env bash
# configure load balancer with HAproxy.

sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend firstbalance\n
       \tbind *:80\n
       \tmode http\n
       \toption forwardfor\n
       \tdefault_backend webservers\n\n
backend webservers\n\
       \tbalance roundrobin\n
       \tserver 1541-web-01 34.75.198.31:80\n
       \tserver 1541-web-02 54.196.188.151:80\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
