#!/usr/bin/env bash
# Script to set http header

sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update
sudo apt install -y haproxy=2.0.\*
lb_config="\n
            frontend http\n
                \tbind *:80\n
                \tmode http\n
                \tdefault_backend web-backend\n
                \n
            backend web-backend\n
                \tbalance roundrobin\n
                \tserver 1541-web-01 34.74.73.47:80 check\n
                \tserver 1541-web-02 35.237.84.2:80 check\n"
echo -e "$lb_config" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart